
<section class="features">
	<div class="grid" style="margin-top:30px">
		<div class="unit">
			<h1>Contacts</h1>
			<p>You can contact the authors and contributors of <strong>Apigility</strong> using the following channels:
				<ul>
					<li>Support is on the mailing list/google group <a href="http://bit.ly/apigility-users">bit.ly/apigility-users</a> and the Freenode IRC channel <strong>"#apigility"</strong>.</li>
					<li>Development discussions occur on the mailing list/google group <a href="http://bit.ly/apigility-dev">bit.ly/apigility-dev</a> and the Freenode IRC channel <strong>"#apigility-dev"</strong>.</li>
					<li>Issues may be reported at the appropriate repositories under the github organization <a href="https://github.com/zfcampus">zfcampus</a>.</li>
					<li>Patches may be submitted via github to the appropriate repositories under <a href="https://github.com/zfcampus">zfcampus</a>.</li>
				</ul>
			</p>
			<h2>Follow us on Twitter</h2>
			<p>You can reach Apigility on Twitter following the <a href="https://twitter.com/Apigility">@Apigility</a> account.
		</div>
	</div>
</section>