
<section class="features">
	<div class="grid" style="margin-top:30px">
		<div class="unit"><article>
			<h1>Contacts</h1>

            <p>
                You can contact the authors and contributors of 
                <strong>Apigility</strong> using the following channels:
			</p>

            <ul>
                <li>
                    Support is on the
                    <a href="https://discourse.zendframework.com/c/questions/apigility">forum</a>
                    and the <a href="https://zendframework-slack.herokuapp.com/">ZendFramework Slack</a> channel <strong>"#apigility"</strong>.
                </li>

                <li>
                    Development discussions occur on the
                    <a href="https://discourse.zendframework.com/c/contributors">forum</a>
                    and the <a href="https://zendframework-slack.herokuapp.com/">ZendFramework Slack</a> channel <strong>"#apigility-contrib"</strong>.
                </li>

                <li>
                    Issues may be reported at the appropriate repositories 
                    under the github organization <a href="https://github.com/zfcampus">zfcampus</a>.
                </li>

                <li>
                    Patches may be submitted via github to the appropriate 
                    repositories under <a href="https://github.com/zfcampus">zfcampus</a>.
                </li>
            </ul>

            <div class="note info">
                <h5>Reporting issues</h5>
                
                <p>
                    Apigility consists of a large number of Zend Framework 2 modules,
                    and thus has many different repositories. If you are unsure which
                    repository to report against, we recommend the following:
                </p>

                <ul>
                    <li>For issues encountered in the administrative user interface,
                        report against <a href="https://github.com/zfcampus/zf-apigility-admin/issues">zfcampus/zf-apigility-admin</a></li>

                    <li>For all other issues, report against
                        <a href="https://github.com/zfcampus/zf-apigility/issues">zfcampus/zf-apigility</a></li>
                </ul>
            </div>

			<h2>Follow us on Twitter</h2>

            <p>
                You can reach Apigility on Twitter by following the 
                <a href="https://twitter.com/Apigility">@Apigility</a> account.
            </p>
		</article></div>
	</div>
</section>
