
<section class="features">
	<div class="grid" style="margin-top:30px">
        <div class="whole">
            <h1>Video</h1>
        </div>
    </div>

	<br clear="left">

	<div class="grid">
		<div class="unit half">
            <div class="media-wrapper">
                <iframe
                    src="https://docs.google.com/a/zend.com/file/d/0B3DjV-SlG3QbajF2aFE0NXdvcTQ/preview"
                    width="400" height="240"></iframe>
            </div>
		</div>

		<div class="unit half">
			<h2>Getting started with Apigility</h2>

            <p>
                In this video, learn how to start using Apigility. Details the
                various features available in Apigility, the world's easiest
                way to build an API. Covers how to create an API, create
                services, add authorization and authentication rules, and
                create validation rules.
            </p>
		</div>
	</div>

	<br clear="left"><br />

	<div class="grid">
		<div class="unit half">
            <div class="media-wrapper">
                <iframe
                    src="https://docs.google.com/a/zend.com/file/d/0B3DjV-SlG3QbVERDUVhfbUpLTFk/preview"
                    width="400" height="240"></iframe>
            </div>
		</div>

		<div class="unit half">
			<h2>Introduction to Documentation</h2>

            <p>
                In this video, learn how to use the Documentation feature of
                Apigility, introduced in version 0.9.
            </p>
		</div>
	</div>

	<br clear="left"><br />
</section>
