<section class="features">
	<div class="grid" style="margin-top:30px">
        <div class="whole">
            <h1 id="pageTitle">Apigility Introduction</h1>
        </div>
    </div>

	<br clear="left">

    <div class="grid" style="padding-left: 10px; margin-top: 20px;">
        <div class="videoContent">
            <video id="agPlayer" controls preload="none" width="960" height="540" style="width: 100%; height: 100%;">
                <source src="http://www.youtube.com/watch?v=ZBSX1AB6LcM" type="video/youtube">
            </video>
        </div>
    </div>

    <br clear="left">

    </section>
