
<section class="features">
	<div class="grid" style="margin-top:30px">
        <div class="whole">
            <h1>Video</h1>
        </div>
    </div>

	<br clear="left">

	<div class="grid">
		<div class="unit half">
            <div class="media-wrapper">
                <iframe 
                    src="//docs.google.com/a/zend.com/file/d/0B3DjV-SlG3QbUnFNMTZ2RnhfSkk/preview" 
                    width="400" height="240"></iframe>
            </div>
		</div>

		<div class="unit half">
			<h2>Getting started with Apigility</h2>

            <p>
                Apigility provides a user interface for describing and 
                configuring your API. It also provides the "plumbing" for enabling your API, 
                taking care of things such as authentication and authorization, content 
                negotiation, HTTP negotiation, and content validation. When you're done, you'll 
                also have a fully documented API, enabling developers who will interact with 
                it.
            </p>

            <p>
                In short, Apigility is the easiest way to build robust, secure, and documented APIs.
            </p>
		</div>
	</div>

	<br clear="left"><br />

	<div class="grid">
		<div class="unit half">
            <div class="media-wrapper">
                <iframe 
                    src="//www.youtube.com/embed/9L9wf12t370" 
                    allowfullscreen
                    width="400" height="225"></iframe>
            </div>
		</div>

		<div class="unit half">
			<h2>Apigility Integration in Zend Studio</h2>

            <p>
                See how Apigility is integrated into <a href="http://www.zend.com/en/products/studio">
                Zend Studio</a>, and how you can leverage Studio to build, test, and debug your APIs!
            </p>
		</div>
	</div>

	<br clear="left"><br />

	<div class="grid">
		<div class="unit half">
            <div class="media-wrapper">
                <iframe
                    src="//docs.google.com/a/zend.com/file/d/0B3DjV-SlG3QbVERDUVhfbUpLTFk/preview"
                    width="400" height="240"></iframe>
            </div>
		</div>

		<div class="unit half">
			<h2>Introduction to Documentation</h2>

            <p>
                In this video, learn how to use the Documentation feature of
                Apigility, introduced in version 0.9.
            </p>
		</div>
	</div>

	<br clear="left"><br />
</section>
