<div class="grid chapter">
    <div class="unit one-third">
        <div class="thumb">
            <a class="vidLink"
                href="http://www.youtube.com/watch?v=<?= $this->id; ?>"
                data-poster="<?= $this->thumbnails['small']['url']; ?>">
                <span class="play">&#9658;</span>
                <div class="overlay"></div>
            </a>
            <img src="<?= $this->thumbnails['small']['url']; ?>" width="100%">
        </div>
    </div>
    <div class="unit two-thirds">
        <a class="vidLink"
            href="http://www.youtube.com/watch?v=<?= $this->id; ?>"
            data-poster="<?= $this->thumbnails['large']['url']; ?>">
            <h2><?= $this->title; ?></h2>
        </a>
        <p><?= $this->description; ?></p>
    </div>
</div>
<br clear="left">
