<?php
$this->inlineScript()->appendFile($this->basePath('/js/manual-toc.js'));
?>
<section class="manual">
    <div class="grid" style="margin-top:30px">
        <div class="unit four-fifths">
            <article>
                <div class="post-content">
                <?= $this->markdownpage($this->page, $this->model) ?>
                </div>
            </article>    
        </div>

        <div class="unit one-fifth">
            <?= $this->partial('documentation/toc', [
                'model'   => $this->model,
                'current' => $this->page,
            ]) ?>
        </div>
    </div>
</section>
