<?php // @codingStandardsIgnoreFile
$this->inlineScript()->appendFile($this->basePath('/js/prism-zf.js'));
$this->headLink()->appendStylesheet($this->basePath('/css/prism-zf.css'));
 ?>
<section class="docs">
	<div class="grid" style="margin-top:30px">
		<div class="unit four-fifths">
			<article>
				<div class="post-content">
					<h1>Download</h1>

                    <p>
                        Download the <strong><?php echo $this->version ?></strong> version of <strong>Apigility</strong>:<br /><br />
						<a href="<?php echo $this->zip ?>"><img src="img/download_zip.png" alt="Zip" title="Zip" class="download responsive"></a>
						<a href="<?php echo $this->tgz ?>"><img src="img/download_tgz.png" alt="Tgz" title="Tgz" class="download responsive"></a>
					</p>

                    <p>
                        After download, you need to extract the .zip (or .tgz) file,
                        go inside the extracted folder and run the following command
                        using <strong>PHP 5.4+</strong>:
                    </p>

                    <pre><code class="language-bash">$ php -S 0.0.0.0:8888 -t public public/index.php</code></pre>

                    <p>
                        You can start <strong>Apigility</strong> opening your
                        browser to <a href="http://localhost:8888">http://localhost:8888</a>
                    </p>

					<div class="note info">
						<h5>If you are using PHP &lt; 5.4</h5>

                        <p>
                            You need to configure a web server to publish the
                            <strong>public</strong> folder of Apigility.
                        </p>
					</div>

                    <div class="note info">
                        <h5>Use any port</h5>

                        <p>
                            While the above command uses port <strong>8888</strong>,
                            you can substitute any available port on your system.
                        </p>
                    </div>

                    <p>
                        You can also install Apigility without downloading
                        the previous package, using the following command in
                        your terminal (make sure your internet connection is
                        enabled):
                    </p>

                    <pre><code class="language-bash">$ curl -sS https://apigility.org/install | php</code></pre>

                    <p>
                        If you do not have <a href="http://curl.haxx.se/">curl</a>
                        installed you can use PHP itself:
                    </p>

                    <pre><code class="language-bash">$ php -r "readfile('https://apigility.org/install');" | php</code></pre>

                    <h2>Install a specific version</h2>
                    
                    <p>
                        If you want to install a specific version of Apigility, you can specify the version in the previous URL path.
                        For instance, if you want to install the 1.2.1 version you need to add <code>/1.2.1</code> at the end of the URL:
                    </p>

                    <pre><code class="language-bash">$ curl -sS https://apigility.org/install/1.2.1 | php</code></pre>

					<div class="note info">
						<h5>If you are using PHP 5.3</h5>

                        <p>
                            If you are using PHP 5.3, the last minor version support that PHP version was 1.2; as such, use the
                            above instructions to install version 1.2.1.
                        </p>
					</div>
				</div>
			</article>
		</div>

		<div class="unit one-fifth hide-on-mobiles">
			<?php echo $this->partial('layout/aside', array(
					'aside'   => $this->aside,
					'current' => $this->current
			)) ?>
		</div>

		<div class="clear"></div>
	</div>
</section>
