<?php $parser = new \League\CommonMark\CommonMarkConverter() ?>
<section class="docs">
    <div class="grid" style="margin-top:30px">
        <div class="unit four-fifths">
            <article>
                <div class="post-content">
                    <h1><?= $this->version ?> Changelog</h1>

                    <?= $parser->convertToHtml($this->changelog) ?>
                </div>
            </article>
        </div>

        <div class="unit one-fifth hide-on-mobiles">
            <?= $this->partial('layout/aside', [
                'aside'   => $this->aside,
                'current' => $this->current,
            ]) ?>
        </div>

        <div class="clear"></div>
    </div>
</section>
