<?= $this->doctype(); ?>
<html>
<head>
    <meta charset="UTF-8">
    <?= $this->headTitle('Apigility')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <?= $this
            ->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ])
            ->appendStylesheet($this->basePath() . '/' . $this->asset('css/styles.css'))
            ->appendStylesheet('https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css')
            ->appendStylesheet('https://cdn.jsdelivr.net/npm/pnotify@4.0.0/dist/PNotifyBrightTheme.css')
            ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css')
    ?>

    <?php
        $this->inlineScript()
            ->prependFile($this->basePath('/') . $this->asset('js/scripts.js'))
            ->prependFile('https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js')
            ->appendFile('https://cdn.jsdelivr.net/npm/pnotify@4.0.0/dist/iife/PNotify.js')
            ->appendFile('https://cdn.jsdelivr.net/npm/pnotify@4.0.0/dist/iife/PNotifyAnimate.js')
            ->appendFile('https://cdn.jsdelivr.net/npm/pnotify@4.0.0/dist/iife/PNotifyButtons.js')
            ->appendFile('https://cdn.jsdelivr.net/npm/pnotify@4.0.0/dist/iife/PNotifyCallbacks.js')
            ->appendFile('https://cdn.jsdelivr.net/npm/pnotify@4.0.0/dist/iife/PNotifyCompat.js')
    ?>
</head>
<body class="wrap">
    <header>
        <nav class="mobile-nav only-on-mobiles">
            <?= $this->navigation('navigation')->menu()->setPartial('layout/menu'); ?>
        </nav>

        <div class="grid">
            <div class="brand unit one-third center-on-mobiles">
                <h1>
                    <a href="<?= $this->url('home') ?>"> 
                    <span>Apigility</span> 
                    <img src="<?= $this->basePath('/img/ag-hero.png') ?>" alt="Apigility" class="responsive"></a>
                </h1>
            </div>

            <nav class="main-nav unit two-thirds hide-on-mobiles">
                <?= $this->navigation('navigation')->menu()->setPartial('layout/menu') ?>
            </nav>
        </div>
    </header>

    <?= $this->content ?>

    <footer>
        <div class="grid">
            <div class="unit half center-on-mobiles">
                <p>
                    &copy; 2013 &mdash; <?= date('Y') ?> by <a href="https://www.zend.com">Zend</a>
                    by <a href="https://www.perforce.com/">Perforce</a>.
                    <br>All rights reserved.
                </p>

                <p>
                    <a href="https://discourse.laminas.dev" class="btn-social" title="Forum"><i class="fa fa-comments"></i></a>
                    <a href="https://laminas.dev/chat" class="btn-social" title="Slack"><i class="fa fa-slack"></i></a>
                    <a href="https://github.com/zfcampus" class="btn-social" title="Github"><i class="fa fa-github"></i></a>
                    <a href="https://twitter.com/apigility" class="btn-social" title="Twitter"><i class="fa fa-twitter"></i></a>
                </p>
            </div>

            <div class="unit half align-right center-on-mobiles">
                <p>
                    Proudly built with
                    <a href="https://framework.zend.com"><img src="<?= $this->basePath('/img/zf.png') ?>"></a>
                </p>
            </div>
        </div>
    </footer>

    <div id="cookie-banner" class="hidden">
        This site uses cookies to allow you to dismiss dialogs. <a href="#" id="cookie-button">Allow Cookies</a>
    </div>

    <?= $this->inlineScript() ?>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
     
      ga('create', 'UA-49458222-1', 'apigility.org');
      ga('send', 'pageview');
    </script>
    <script type="text/javascript">
        (function () {
            const createCookie = function (name, days) {
                if (name !== 'ALLOW_COOKIES' && ! getCookie('ALLOW_COOKIES')) {
                    return;
                }
                const expires = new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * days);
                const cookie = name + "=1;expires=" + expires.toGMTString() + ";";
                document.cookie = cookie;
            };

            const getCookie = function (name) {
                const re = new RegExp('(?:^|;\\s*)' + name + '=(.*?)(?:;|$)', 'g');
                const result = re.exec(document.cookie);
                return (result === null) ? null : result[1];
            };

            const showNotice = function () {
                if (getCookie('LAMINAS_NOTIFIER') !== null) {
                    return;
                }

                const text = 'Apigility is now <a href="https://api-tools.getlaminas.org"><strong>Laminas API Tools</strong></a>. Please update your bookmarks.<br /><br /><small>(Unless you accept cookies, this notice will appear on every page.)</small>';

                const notice = PNotify.notice({
                    title: "We've moved!",
                    text: text,
                    textTrusted: true,
                    hide: false,
                    modules: {
                        Animate: {
                            animate: true,
                            inClass: "swing",
                            outClass: "fadeOutUp",
                        },
                        Buttons: {
                            closer: false,
                            sticker: false
                        }
                    }
                });
                notice.on('click', function () {
                    createCookie('LAMINAS_NOTIFIER', 7);
                    notice.close();
                });
            };

            const showCookieBar = function () {
                if (getCookie('ALLOW_COOKIES')) {
                    return;
                }
                $('#cookie-banner').removeClass('hidden');
                $('#cookie-button').click(function () {
                    createCookie('ALLOW_COOKIES', 90);
                    $('#cookie-banner').addClass('hidden');
                });
            };

            showCookieBar();
            showNotice();
        })();
    </script>
</body>
</html>
